name: Build Debug APK and Share on Telegram

on:
  push:
    branches:
      - telegram

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Check APK existence
        run: find app/build/outputs/ -name "*.apk"

      - name: Set APK permissions
        run: chmod +r app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug

      - name: Verify downloaded APK
        run: ls -l app/build/outputs/apk/debug/

      - name: Send APK to Telegram
#        if: ${{ secrets.SHARE_APK_TO_TELEGRAM == 'true' }}

        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        if: contains(github.event.head_commit.message, 'SHARE_APK')
        run: |
          curl -F chat_id=$TELEGRAM_CHAT_ID \
               -F document=@app/build/outputs/apk/debug/app-debug.apk \
               https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
